# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1db123916651f005f7738762ddc5f8462196bce84990b3236b90f700a2f4e974783c80e2474b1c64337238b8d6e8fac2fd48f07d8711814a4c7c0a6537ca003d

test:
  secret_key_base: a392ee5e6e974818b8af880df12c07a452ddba0b282a0b837ebc3273213df892e3bc219846bced1005e0576d44c88dd989784bc5b1958e6a3bc777c76d7b2f5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
